### ISSUE TITLE
emsinsy bug stop in 準備しています...

### ISSUE THREAD

**Issue by YuzukiTsuru** [oov/emsinsy#1]
fetch.then.then.voice @ emsinsy.js:19
Promise.then (async) 
onmessage  @  emsinsy.js:6

**Comment by YuzukiTsuru** [comment]
![tim 20180501130206](https://user-images.githubusercontent.com/12003087/39461784-e1a61e9c-4d3f-11e8-804a-8dade5c93f80.png)

**Comment by oov** [comment]
I cannot reproduce it.

What are you trying to do?
If you want to run emsinsy on your computer, please refer this branch.
https://github.com/oov/emsinsy/tree/gh-pages
It contains required files to run.

**Comment by YuzukiTsuru** [comment]
I want to use it on https://oov.github.io/emsinsy/  But I can not use it because a bug was stoped it. 
![tim 20180502111502](https://user-images.githubusercontent.com/12003087/39503780-4932c8d4-4dfa-11e8-9b96-e7cd0ba47561.png)

**Comment by oov** [comment]
Hmm...
I cannot reproduce it yet so I don't know why caused.

![screen](https://user-images.githubusercontent.com/270909/39504669-284948d8-4e08-11e8-8ec5-648a82415f35.PNG)
Have you received these files correctly?
I think that some files are broken in your environment.

**Comment by YuzukiTsuru** [comment]
emmm.私はchromでやってみましたが、やはり同じミスですが、EDGEの力はできます。まさかchromを支持しないのか？

**Comment by YuzukiTsuru** [comment]
わかりました、 asm.jsは禁止されました。
